disabled_rules:
  - file_length
  - line_length
  - redundant_void_return
  - todo
  - type_body_length

included:
  - Cryptomator
  - CryptomatorTests
  - CryptomatorCommon
  - CryptomatorCommonHostedTests
  - CryptomatorFileProvider
  - CryptomatorFileProviderTests
  - FileProviderExtension
  - FileProviderExtensionUI

excluded:
  - CryptomatorCommon/.build

identifier_name:
  min_length: 1
  max_length: 50
inclusive_language:
  override_allowed_terms: ["masterkey"]
type_name:
  max_length: 50
  allowed_symbols: "_"
