fastlane_version("2.206.2")

default_platform(:ios)

platform :ios do
  desc "Sync certificates and provisioning profiles for all targets"
  lane :certificates do
    match(type: "appstore")
    match(type: "development", force_for_new_devices: true)
  end

  desc "Create screenshots in every language with every device"
  lane :create_screenshots do
    snapshot
  end

  desc "Upload screenshots to App Store Connect"
  lane :upload_screenshots do
    deliver(skip_binary_upload: true, skip_metadata: true, overwrite_screenshots: true, run_precheck_before_submit: false)
  end

  desc "Update metadata in App Store Connect"
  lane :update_metadata do
    deliver(skip_binary_upload: true, skip_screenshots: true, run_precheck_before_submit: false)
  end

  desc "Runs all the tests"
  lane :test do
    scan(open_report: true)
  end

  desc "Submit a new beta build to TestFlight"
  lane :beta do
    scan
    gym
    changelog = File.read("changelog.txt")
    pilot(changelog: changelog, distribute_external: true, groups: ["External Testers"])
    version = get_version_number(target: "Cryptomator")
    build = `git rev-list --count $(git rev-parse --abbrev-ref HEAD) | tr -d " \t\n\r"`
    slack(
      default_payloads: [], # reduce the notification to the minimum
      message: "Successfully submitted version #{version} (#{build}) to TestFlight :cryptomator:",
      payload: {
        "Changes" => changelog
      }
    )
  end

  desc "Deploy a new version to the App Store"
  lane :app_store do
    scan
    gym
    changelog = File.read("changelog.txt")
    deliver(skip_screenshots: true, submit_for_review: true, submission_information: { add_id_info_uses_idfa: false })
    version = get_version_number(target: "Cryptomator")
    build = `git rev-list --count $(git rev-parse --abbrev-ref HEAD) | tr -d " \t\n\r"`
    slack(
      default_payloads: [], # reduce the notification to the minimum
      message: "Successfully deployed version #{version} (#{build}) to the App Store :cryptomator:",
      payload: {
        "Changes" => changelog
      }
    )
  end

  """
  Updates the app identifier and bundle identifier of the following targets:
  - Cryptomator
  - FileProviderExtension
  - FileProviderExtensionUI
  - CryptomatorIntents
  The app identifier and bundle identifier of the Cryptomator target are set to the same value.
  The bundle identifier of the ofther targets are set to the bundle_identifier + the lowercased target name.
  The display name can be passed as an option and is the same for all targets.
  The app group is set to the app_group option. 
  The keychain sharing group is set to the keychain_group option with the prefix $(AppIdentifierPrefix).
  Updates the constants file to conveniently use the app group inside the Swift code.
  Sets the app icon to the file at the passed app_icon_file_path.
  """
  desc "Update app settings to release a different version"
  lane :update_app do |options|
    app_identifier = options[:app_identifier]
    bundle_identifier = options[:bundle_identifier]
    keychain_group = options[:keychain_group]
    app_icon_file_path = options[:app_icon_file_path]

    # Update the app identifier and bundle identifier
    update_app_identifier(
      xcodeproj: "Cryptomator.xcodeproj",
      plist_path: "Cryptomator/Info.plist",
      app_identifier: app_identifier
    )
    update_app_identifier(
      xcodeproj: "Cryptomator.xcodeproj",
      plist_path: "FileProviderExtension/Info.plist",
      app_identifier: "#{bundle_identifier}.fileprovider"
    )
    update_app_identifier(
      xcodeproj: "Cryptomator.xcodeproj",
      plist_path: "FileProviderExtensionUI/Info.plist",
      app_identifier: "#{bundle_identifier}.fileprovider-ui"
    )
    update_app_identifier(
      xcodeproj: "Cryptomator.xcodeproj",
      plist_path: "CryptomatorIntents/Info.plist",
      app_identifier: "#{bundle_identifier}.intents"
    )
    update_app_identifier(
      xcodeproj: "Cryptomator.xcodeproj",
      plist_path: "CryptomatorTests/Info.plist",
      app_identifier: "#{bundle_identifier}.tests"
    )

    # Update the display name
    update_info_plist(
      xcodeproj: "Cryptomator.xcodeproj",
      plist_path: "Cryptomator/Info.plist",
      display_name: options[:display_name]
    )
    update_info_plist(
      xcodeproj: "Cryptomator.xcodeproj",
      plist_path: "FileProviderExtension/Info.plist",
      display_name: options[:display_name]
    )
    update_info_plist(
      xcodeproj: "Cryptomator.xcodeproj",
      plist_path: "FileProviderExtensionUI/Info.plist",
      display_name: options[:display_name]
    )

    update_info_plist(
      xcodeproj: "Cryptomator.xcodeproj",
      plist_path: "CryptomatorIntents/Info.plist",
      display_name: options[:display_name]
    )

    # Update the NSExtensionFileProviderDocumentGroup
    update_info_plist(
      xcodeproj: "Cryptomator.xcodeproj",
      plist_path: "FileProviderExtension/Info.plist",
      block: proc do |plist|
        plist["NSExtension"]["NSExtensionFileProviderDocumentGroup"] = options[:app_group]
      end
    )

    # Update the app group for the Cryptomator target
    update_app_group_identifiers(
      entitlements_file: "Cryptomator/Cryptomator.entitlements",
      app_group_identifiers: [options[:app_group]]
    )

    # Update the app group for the CryptomatorIntents target
    update_app_group_identifiers(
      entitlements_file: "CryptomatorIntents/CryptomatorIntents.entitlements",
      app_group_identifiers: [options[:app_group]]
    )

    # Update the app group for the FileProviderExtension target
    update_app_group_identifiers(
      entitlements_file: "FileProviderExtension/FileProviderExtension.entitlements",
      app_group_identifiers: [options[:app_group]]
    )

    # Update the app group for the FileProviderExtensionUI target
    update_app_group_identifiers(
      entitlements_file: "FileProviderExtensionUI/FileProviderExtensionUI.entitlements",
      app_group_identifiers: [options[:app_group]]
    )
    
    # Update the keychain sharing group for the Cryptomator target
    update_keychain_access_groups(
      entitlements_file: "Cryptomator/Cryptomator.entitlements",
      identifiers: ["$(AppIdentifierPrefix)#{keychain_group}"]
    )

    # Update the keychain sharing group for the FileProviderExtension target
    update_keychain_access_groups(
      entitlements_file: "FileProviderExtension/FileProviderExtension.entitlements",
      identifiers: ["$(AppIdentifierPrefix)#{keychain_group}"]
    )

    # Update the keychain sharing group for the FileProviderExtensionUI target
    update_keychain_access_groups(
      entitlements_file: "FileProviderExtensionUI/FileProviderExtensionUI.entitlements",
      identifiers: ["$(AppIdentifierPrefix)#{keychain_group}"]
    )

    # Update the app constants file.
    sh("./scripts/create-app-constants.sh  #{bundle_identifier}")

    # Update the app icon.
    sh("./scripts/create-app-icon.sh  #{app_icon_file_path}")
  end

    error do |lane, exception|
    # slack(message: exception.to_s, success: false)
  end
end
