# A list of devices you want to take the screenshots from
devices([
  "iPhone 13 Pro Max",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch) (5th generation)",
  "iPad Pro (12.9-inch) (2nd generation)",
])

languages([
  "en-US",
  "de-DE",
])

# The name of the scheme which contains the UI Tests
scheme("Snapshots")

# Set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

localize_simulator(true)

disable_slide_to_type(true)

xcargs("SWIFT_ACTIVE_COMPILATION_CONDITIONS='$(inherited) SNAPSHOTS'")

# Erasing the simulator is necessary to bring the Files App to its original state
erase_simulator(true)

# Uncomment below for debugging
# clear_previous_screenshots(true)
# Set derived data path for faster debug builds
# derived_data_path("")
# Show Simualtor
# headless(false)
