#!/bin/sh

# Path is relative to the fastlane folder
cat > ../CryptomatorCommon/Sources/CryptomatorCommonCore/CryptomatorConstants.swift << EOM
//
//  CryptomatorConstants.swift
//  CryptomatorCommonCore
//
//  This file was automatically generated by create-app-constants.sh and should not be modified.
//

import Foundation

public enum CryptomatorConstants {
	public static let appGroupName = "group.${1}"
	public static let mainAppBundleId = "${1}"
}
EOM
