//
//  CryptomatorConstants.swift
//  CryptomatorCommonCore
//
//  This file was automatically generated by create-app-constants.sh and should not be modified.
//

import Foundation

public enum CryptomatorConstants {
	public static let appGroupName = "group.org.cryptomator.ios"
	public static let mainAppBundleId = "org.cryptomator.ios"
}
